# syntax=docker/dockerfile:1

# ---- build stage ----
  FROM golang:1.25-alpine AS build
  WORKDIR /src
  
  RUN apk add --no-cache ca-certificates git
  
  COPY go.mod go.sum ./
  RUN --mount=type=cache,target=/go/pkg/mod \
      go mod download
  
  COPY . .
  
  # build a static-ish binary
  RUN --mount=type=cache,target=/root/.cache/go-build \
      CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
      go build -trimpath -ldflags="-s -w" -o /out/app ./cmd/main.go
  
  # ---- runtime stage ----
  FROM alpine:3.20
  RUN apk add --no-cache ca-certificates
  
  WORKDIR /app
  COPY --from=build /out/app /app/app
  
  EXPOSE 8080
  USER 65532:65532
  
  ENTRYPOINT ["/app/app"]
  